# vim:fileencoding=utf-8:foldmethod=marker
include ~/.config/omarchy/current/theme/kitty.conf

allow_remote_control yes
bold_font        auto
bold_italic_font auto
clear_all_shortcuts yes
confirm_os_window_close 0
cursor_shape block
enable_audio_bell no
font_size 12
hide_window_decorations yes
italic_font      auto
map cmd+f    toggle_fullscreen
map cmd+v       paste_from_clipboard
map ctrl+cmd+r load_config_file
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard
mouse_hide_wait 1.0
show_window_resize_notification no
single_instance yes
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
visual_bell_duration 0
window_padding_height 14
window_padding_width 14
map ctrl+shift+c       copy_to_clipboard
map ctrl+shift+v       paste_from_clipboard
cursor_trail 1
map ctrl+k             clear_terminal scroll active
